# -*- coding: utf-8 -*-
{
    'name': 'Alze CRM Personalización',
    'version': '17.0.1.0.0',
    'category': 'Sales/CRM',
    'summary': 'Gestión de rutas geográficas, clientes y choferes',
    'depends': ['base', 'crm', 'web', 'hr', 'base_geolocalize', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'views/crm_partner_views.xml',
        'views/alze_route_views.xml',
        'views/alze_driver_views.xml',
        'views/crm_lead_views.xml',
        'views/crm_menu_routes.xml',
        'views/crm_menu_driver.xml',
        'views/hr_employee_view_button.xml',
        'views/alze_product_views.xml',
        'views/crm_lead_order_views.xml',
        'views/alze_vehicle_views.xml',
        'views/crm_menu_vehicle.xml',
        'views/alze_samsara_route_views.xml',
        'views/crm_menu_samsara.xml',
        'views/alze_start_point_views.xml',
        'views/crm_menu_start_point.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'alze_crm/static/lib/leaflet/leaflet.css',
            'alze_crm/static/lib/leaflet/leaflet.js',
            'alze_crm/static/lib/leaflet/leaflet.draw.css',
            'alze_crm/static/lib/leaflet/leaflet.draw.js',
            'alze_crm/static/src/js/route_map_widget.js',
            'alze_crm/static/src/xml/route_map_widget.xml',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}