from . import res_partner
from . import res_partner_route
from . import crm_lead
from . import crm_lead_extend
from . import alze_route
from . import alze_driver
from . import alze_driver_vehicle
from . import hr_employee_extend
from . import alze_product_template
from . import alze_product_variant
from . import crm_lead_order
from . import alze_route_schedule
from . import alze_start_point
from . import alze_samsara_route